### ISSUE TITLE
Improper handling of enum descriptions on parameter tokens

### ISSUE THREAD

**Issue by erunion** [vimeo/mill#234]
```
* @api-queryParam:public {filter}
*      + Members
*          - `embeddable`
*          - `conditional_featured` - Featured (promoted) videos
```

```
-
    description: "The attribute by which to filter the results.\n\nOption descriptions:\n * `conditional_featured` - Featured (promoted) videos\n"
    in: query
    name: filter
    required: false
    schema:
    type: string
    enum:
        - conditional_featured
        - embeddable
```
